services:
  connect:
    build: .
    container_name: iceberg-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: iceberg-configs
      OFFSET_STORAGE_TOPIC: iceberg-offsets 
      HOST_NAME: "0.0.0.0"
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
