services:
  connect:
    image: quay.io/yugabyte/debezium-connector:1.7.0.13-7-BETA-SNAPSHOT
    container_name: iceberg-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: ${BOOTSTRAP_SERVERS}
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: iceberg-configs
      OFFSET_STORAGE_TOPIC: iceberg-offsets 
      HOST_NAME: "0.0.0.0"
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      - ./kafka-connect-iceberg-sink-0.1.3-shaded.jar:/kafka/connect/kafka-connect-iceberg-sink-0.1.3-shaded.jar 
