version: "3"
services:
  kafka-connect:
    build:
      context: ./jmx-exporter
    container_name: kafka-connect
    ports:
      - 8083:8083
      - 9875:9875
      - 9876:9876
    environment:
      BOOTSTRAP_SERVERS: ${KAFKA_HOST}
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: kafka-connect_configs
      OFFSET_STORAGE_TOPIC: kafka-connect_offset
      STATUS_STORAGE_TOPIC: kafka-connect_status
      HOST_NAME: "0.0.0.0"
      REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_REST_PORT: 8083
      KAFKA_JMX_PORT: '9875'
      KAFKA_OPTS: "-javaagent:/kafka/etc/jmx_prometheus_javaagent-0.9.jar=9876:/etc/jmx-exporter/kafka-connect.yml"
