{
 "title": "CDC Health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Queue size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_currentqueuesizeinbytes{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queue remaining capacity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM GC Pause",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to expiry of stream",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "cdcsdk_expiry_time_ms", "legendFormat": "__auto" }
   ]
  }
 ]
}