{
 "title": "Monitoring CDC Operations",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Change event count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sent lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "cdcsdk_sent_lag_micros", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "committed lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "cdcsdk_committed_lag_micros", "legendFormat": "__auto" }
   ]
  }
 ]
}