{
 "title": "Snapshot Mode",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total number of events seen",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Table count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Table count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}