{
 "title": "CDC Health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "cdcsdk_expiry_time_ms",
   "type": "timeseries",
   "description": "Expiry time of stream",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "cdcsdk_expiry_time_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "jvm_gc_collection_seconds_sum",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "debezium_metrics_currentqueuesizeinbytes",
   "type": "stat",
   "description": "The current volume, in bytes, of records in the queue.\n\n",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_currentqueuesizeinbytes{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "debezium_metrics_queueremainingcapacity",
   "type": "stat",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}