{
 "title": "Metrics dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "debezium_metrics_totalnumberofeventsseen aggregated on partition level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(partition) (debezium_metrics_totalnumberofeventsseen{context=\"streaming\"})",
     "legendFormat": "count for {{partition}}"
    },
    {
     "expr": "sum by(partition) (rate(debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}[$__rate_interval]))",
     "legendFormat": "rate for {{partition}}"
    }
   ]
  },
  {
   "title": "debezium_metrics_totalnumberofeventsseen aggregated on connector level ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (debezium_metrics_totalnumberofeventsseen{context=\"streaming\"})",
     "legendFormat": "count for {{name}}"
    },
    {
     "expr": "sum by(name) (rate(debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}[1m]))",
     "legendFormat": "rate for {{name}}"
    }
   ]
  },
  {
   "title": "Change event count",
   "type": "timeseries",
   "description": "Number of change events sent by cdc service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stream expiry time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "cdcsdk_expiry_time_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "debezium_metrics_totalnumberofeventsseen",
   "type": "stat",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "debezium_metrics_currentqueuesizeinbytes",
   "type": "stat",
   "description": "The current volume, in bytes, of records in the queue.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_currentqueuesizeinbytes{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "cdcsdk_sent_lag_micros", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "debezium_metrics_queueremainingcapacity",
   "type": "stat",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}