{
 "title": "Monitoring CDC operations",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "cdcsdk_change_event_count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cdcsdk_traffic_sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cdcsdk_sent_lag_micros",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    { "expr": "cdcsdk_sent_lag_micros", "legendFormat": "__auto" }
   ]
  }
 ]
}