{
 "title": "Performance Evaluation",
 "time": { "from": "2022-09-21T07:03:36.994Z", "to": "2022-09-21T07:14:03.295Z" },
 "panels": [
  {
   "title": "Records sent by client to sink",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent by CDC service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Records sent by cdc service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  }
 ]
}