{
 "title": "Snapshot mode",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "debezium_metrics_totalnumberofeventsseen",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "debezium_metrics_totaltablecount",
   "type": "stat",
   "description": "The total number of tables that are being included in the snapshot.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totaltablecount{context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "debezium_metrics_remainingtablecount",
   "type": "stat",
   "description": "The number of tables that the snapshot has yet to copy.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_remainingtablecount{context=\"snapshot\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}