{
 "title": "Kafka Connect Metrics Dashboard",
 "description": "Monitor Apache Kafka Connect",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "env", "label": "Environment", "query": { "query": "label_values(env)" } },
   {
    "name": "kafka_connect_cluster_id",
    "label": "Cluster ID",
    "query": {
     "query": "label_values(kafka_connect_cluster_id)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_connect_app_info{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},instance)"
    }
   },
   {
    "name": "connector",
    "label": "Connector name",
    "query": {
     "query": "label_values(kafka_connect_connector_task_metrics_pause_ratio{job=\"kafka-connect\", env=\"$env\",kafka_connect_cluster_id=~\"$kafka_connect_cluster_id\"},connector)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Tasks Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_total_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_running_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_paused_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_failed_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unassigned Tasks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_unassigned_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Destroyed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_destroyed_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_connector_status",
     "legendFormat": "{{connector}} - {{status}} - task = {{task}}"
    }
   ]
  },
  {
   "title": "Task repartition per status",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_running_task_count",
     "legendFormat": "running"
    },
    {
     "expr": "kafka_connect_worker_connector_failed_task_count",
     "legendFormat": "failed"
    },
    {
     "expr": "kafka_connect_worker_connector_paused_task_count",
     "legendFormat": "paused"
    },
    {
     "expr": "kafka_connect_worker_connector_unassigned_task_count",
     "legendFormat": "unassigned"
    },
    {
     "expr": "kafka_connect_worker_connector_destroyed_task_count",
     "legendFormat": "destroyed"
    }
   ]
  },
  {
   "title": "Status of connectors",
   "type": "timeseries",
   "description": "Status of connectors over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "kafka_connect_connector_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Status of tasks",
   "type": "timeseries",
   "description": "Status of tasks over time",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_worker_connector_running_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_worker_connector_paused_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_worker_connector_failed_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_worker_connector_unassigned_task_count",
     "legendFormat": "__auto"
    },
    {
     "expr": "kafka_connect_worker_connector_destroyed_task_count",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CDC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "cdcsdk_change_event_count",
   "type": "timeseries",
   "description": "Number of change events sent by the cdc service",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stream expiry time (ms)",
   "type": "timeseries",
   "description": "Expiry time of the stream",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expr": "cdcsdk_expiry_time_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cdcsdk_traffic_sent ",
   "type": "timeseries",
   "description": "Ammount of data sent by the cdc service",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "debezium_metrics_totalnumberofeventsseen",
   "type": "timeseries",
   "description": "The total number of events that this connector has seen since the last start or metrics reset.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(name) (rate(debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}[1m]))",
     "legendFormat": "rate for connector = {{name}}"
    },
    {
     "expr": "sum by(name) (debezium_metrics_totalnumberofeventsseen{context=\"streaming\"})",
     "legendFormat": "sum for connector = {{name}}"
    }
   ]
  },
  {
   "title": "Sent lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 7, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "cdcsdk_sent_lag_micros", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "debezium_metrics_currentqueuesizeinbytes",
   "type": "stat",
   "description": "The current volume, in bytes, of records in the queue.\n\n",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_currentqueuesizeinbytes{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "debezium_metrics_queueremainingcapacity",
   "type": "stat",
   "description": "The free capacity of the queue used to pass events between the streamer and the main Kafka Connect loop.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_queueremainingcapacity{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (jvm_memory_bytes_used)",
     "legendFormat": "memory used"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\"}",
     "legendFormat": "max memory used"
    }
   ]
  },
  {
   "title": "JVM GC time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(jvm_gc_collection_seconds_sum[5m]))",
     "legendFormat": "{{kafka_connect_cluster_id}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Connect Worker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connect Worker",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_connect_worker_connector_count)",
     "legendFormat": "kafka_connect_worker_connector_count"
    },
    {
     "expr": "sum by(instance) (kafka_connect_worker_connector_startup_success_total)",
     "legendFormat": "kafka_connect_worker_connector_startup_success_total"
    },
    {
     "expr": "sum by(instance) (kafka_connect_worker_connector_startup_failure_total)",
     "legendFormat": "kafka_connect_worker_connector_startup_failure_total"
    },
    {
     "expr": "sum by(instance) (kafka_connect_worker_connector_total_task_count)",
     "legendFormat": "kafka_connect_worker_connector_total_task_count"
    },
    {
     "expr": "sum by(instance) (kafka_connect_worker_task_startup_success_total)",
     "legendFormat": "kafka_connect_worker_task_startup_success_total"
    },
    {
     "expr": "sum by(instance) (kafka_connect_worker_connector_startup_failure_total)",
     "legendFormat": "kafka_connect_worker_connector_startup_failure_total"
    }
   ]
  },
  {
   "title": "Network IO Rate",
   "type": "graph",
   "description": "Average number of network operations (reads or writes) on all connections per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    { "expr": "kafka_connect_network_io_rate", "legendFormat": "{{instance}}-{{client_id}}" }
   ]
  },
  {
   "title": "Incoming Byte Rate",
   "type": "graph",
   "description": "Bytes per second read off all sockets",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_incoming_byte_rate",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Outgoing Byte Rate",
   "type": "graph",
   "description": "Average number of outgoing bytes sent per second to all servers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_outgoing_byte_rate",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current number of active connections",
   "type": "graph",
   "description": "Current number of active connections",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    { "expr": "kafka_connect_connection_count", "legendFormat": "{{instance}}-{{client_id}}" }
   ]
  },
  {
   "title": "Failed authentication connections",
   "type": "graph",
   "description": "Connections that failed authentication",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_failed_authentication_total",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Success authentication connections",
   "type": "graph",
   "description": "Connections that were successfully authenticated using SASL or SSL",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "yaxes": [
    { "format": "connections" }
   ],
   "targets": [
    {
     "expr": "kafka_connect_successful_reauthentication_rate",
     "legendFormat": "{{instance}}-{{client_id}}"
    }
   ]
  },
  {
   "title": "Average number of requests",
   "type": "graph",
   "description": "Average number of requests sent per second",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "kafka_connect_request_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Responses received and sent",
   "type": "graph",
   "description": "Responses received and sent per second",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    { "expr": "kafka_connect_response_rate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IO Ratio",
   "type": "graph",
   "description": "Fraction of time the I/O thread spent doing I/O",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "kafka_connect_io_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Connector details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connectors",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(connector) (kafka_connect_worker_connector_total_task_count)",
       "legendFormat": "kafka_connect_worker_connector_total_task_count"
      },
      {
       "expr": "sum by(connector) (kafka_connect_worker_connector_failed_task_count)",
       "legendFormat": "kafka_connect_worker_connector_failed_task_count"
      },
      {
       "expr": "sum by(connector) (kafka_connect_worker_connector_paused_task_count)",
       "legendFormat": "kafka_connect_worker_connector_paused_task_count"
      },
      {
       "expr": "sum by(connector) (kafka_connect_worker_connector_destroyed_task_count)",
       "legendFormat": "kafka_connect_worker_connector_destroyed_task_count"
      },
      {
       "expr": "sum by(connector) (kafka_connect_worker_connector_unassigned_task_count)",
       "legendFormat": "kafka_connect_worker_connector_unassigned_task_count"
      }
     ]
    }
   ]
  },
  {
   "title": "Rebalances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 },
   "targets": [
    {}
   ]
  },
  {
   "title": "($instance) Time since last rebalance ",
   "type": "stat",
   "description": "Time since last rebalance",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 92 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_connect_worker_rebalance_time_since_last_rebalance_ms >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Batch Size Average",
   "type": "timeseries",
   "description": "Average size of the batches processed by the connector",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_batch_size_avg",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Offset commit Average Time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to commit offsets",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_offset_commit_avg_time_ms",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Running ratio",
   "type": "timeseries",
   "description": "The fraction of time this task has spent in the running state.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kafka_connect_connector_task_running_ratio",
     "legendFormat": "{{{{connector}}-{{task}}}}"
    }
   ]
  },
  {
   "title": "Task Errors metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total record failures",
   "type": "timeseries",
   "description": "Total number of failures seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_failures",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record errors",
   "type": "timeseries",
   "description": "Total number of errors seen by task",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_record_errors",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total record skipped",
   "type": "timeseries",
   "description": "Total number of records skipped by task",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_records_skipped",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total errors logged",
   "type": "timeseries",
   "description": "The number of messages that was logged into either the dead letter queue or with Log4j",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_errors_logged",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Total retries",
   "type": "timeseries",
   "description": "Total number of retries made by task",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_total_retries",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Dead letter queue Produce requests",
   "type": "timeseries",
   "description": "Number of produce requests to the dead letter queue",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kafka_connect_task_error_deadletterqueue_produce_requests",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Poll Batch Average time",
   "type": "timeseries",
   "description": "The average time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_avg_time_ms",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Poll Batch Max time",
   "type": "timeseries",
   "description": "The maximum time in milliseconds taken by this task to poll for a batch of source records",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_poll_batch_max_time_ms",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Poll rate",
   "type": "timeseries",
   "description": "The average per-second number of records produced/polled (before transformation) by this task belonging to the named source connector in this worker.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_poll_rate",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Write rate",
   "type": "timeseries",
   "description": "The average per-second number of records output from the transformations and written to Kafka for this task belonging to the named source connector in this worker. This is after transformations are applied and excludes any records filtered out by the transformations.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_connect_source_task_source_record_write_rate",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Source Record Active Count average",
   "type": "timeseries",
   "description": "The average number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(task) (kafka_connect_source_task_source_record_active_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Source Record Active Count max",
   "type": "timeseries",
   "description": "The maximum number of records that have been produced by this task but not yet completely written to Kafka.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by(task) (kafka_connect_source_task_source_record_active_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sink metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Partition Count",
     "type": "stat",
     "description": "The number of topic partitions assigned to this task belonging to the named sink connector in this worker.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_partition_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Put Batch Average time",
     "type": "timeseries",
     "description": "The average time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_put_batch_avg_time_ms",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Put Batch Max time",
     "type": "timeseries",
     "description": "The maximum time in milliseconds taken by this task to put a batch of sinks records",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 203 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "kafka_connect_sink_task_put_batch_max_time_ms",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}