# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/user.proto\"a\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t\x12\x12\n\nbirth_date\x18\x04 \x01(\t\x12\x17\n\x06source\x18\x05 \x01(\x0e\x32\x07.Source*0\n\x06Source\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08LINKEDIN\x10\x01\x12\x0b\n\x07TWITTER\x10\x02\x42+\n\x1e\x63om.example.protobuftest.protoB\tUserProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\036com.example.protobuftest.protoB\tUserProto'
  _globals['_SOURCE']._serialized_start=119
  _globals['_SOURCE']._serialized_end=167
  _globals['_USER']._serialized_start=20
  _globals['_USER']._serialized_end=117
# @@protoc_insertion_point(module_scope)
