{
 "title": "Performance Evaluation",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "debezium_metrics_totalnumberofeventsseen",
   "type": "stat",
   "description": "The total number of events that this connector has seen since the last start or metrics reset.\n\n",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debezium_metrics_totalnumberofeventsseen{context=\"streaming\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cdcsdk_traffic_sent",
   "type": "timeseries",
   "description": "Data sent by cdc service",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "cdcsdk_traffic_sent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "cdcsdk_change_event_count",
   "type": "timeseries",
   "description": "Change events sent by cdc service",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "cdcsdk_change_event_count", "legendFormat": "__auto" }
   ]
  }
 ]
}